### ISSUE TITLE
SIGMA HATAR

### ISSUE THREAD

**Issue by MelihGMC2** [chocopie69/Minecraft-Hacked-Client-Sources#2]
WHY LEAK SIGMA SOURCE

**Comment by chocopie69** [comment]
NO IT IS FAKE SIGMA SOURCE. REAL SIGMA SOURCE CAN'T BE LEAKED OMIKRON ALLAH BEST!

**Comment by MelihGMC2** [comment]
sigma allah don't leak sigms source it's haram

**Comment by yourfriendoss** [comment]
sigma best dont leak its haram
