### ISSUE TITLE
where is Sigma Jello source code

### ISSUE THREAD

**Issue by SigmaBootstrapper** [chocopie69/Minecraft-Hacked-Client-Sources#3]
trash repository im like balls

**Comment by chocopie69** [comment]
I will private this repo if you don't stop being a hatar

**Comment by MelihGMC2** [comment]
Omikron obfustucation is so powerful that you can't deobfuscate sigma jello 5.0

**Comment by Godwhitelight** [comment]
SigmaBootstrapper your mom is trush.

chocopie69 dont remove this repo. he is dumb.

**Comment by SigmaBootstrapper** [comment]
> SigmaBootstrapper your mom is trush.
> 
> chocopie69 dont remove this repo. he is dumb.

what is trush

**Comment by MelihGMC2** [comment]
> > SigmaBootstrapper your mom is trush.
> > chocopie69 dont remove this repo. he is dumb.
> 
> what is trush

misspell of the word "trash"

**Comment by SigmaBootstrapper** [comment]
> > > SigmaBootstrapper your mom is trush.
> > > chocopie69 dont remove this repo. he is dumb.
> > 
> > 
> > what is trush
> 
> misspell of the word "trash"

what? my mom isnt misspell of the word "trash". my mom is linda

**Comment by MelihGMC2** [comment]
> > > > SigmaBootstrapper your mom is trush.
> > > > chocopie69 dont remove this repo. he is dumb.
> > > 
> > > 
> > > what is trush
> > 
> > misspell of the word "trash"
> 
> what? my mom isnt misspell of the word "trash". my mom is linda

if you have understanding problems, let me tell he meant your mom is trash

**Comment by SigmaBootstrapper** [comment]
> > > > > SigmaBootstrapper your mom is trush.
> > > > > chocopie69 dont remove this repo. he is dumb.
> > > > 
> > > > 
> > > > what is trush
> > > 
> > > 
> > > misspell of the word "trash"
> > 
> > 
> > what? my mom isnt misspell of the word "trash". my mom is linda
> 
> if you have understanding problems, let me tell he meant your mom is trash

she isn't trash.. she is linda

**Comment by MelihGMC2** [comment]
> > > > > > SigmaBootstrapper your mom is trush.
> > > > > > chocopie69 dont remove this repo. he is dumb.
> > > > > 
> > > > > 
> > > > > what is trush
> > > > 
> > > > 
> > > > misspell of the word "trash"
> > > 
> > > 
> > > what? my mom isnt misspell of the word "trash". my mom is linda
> > 
> > if you have understanding problems, let me tell he meant your mom is trash
> 
> she isn't trash.. she is linda

ok cool

**Comment by MelihGMC2** [comment]
also you should know that this repository isn't trash, it's minecraft hacked client sources

**Comment by chocopie69** [comment]
@MelihGMC2  he's natasha (angles), and he looks at this shit like everyday to skid for kino clarinet

**Comment by MelihGMC2** [comment]
> @MelihGMC2  he's natasha (angles), and he looks at this shit like everyday to skid for kino clarinet 

that's kinda sigma hatar

**Comment by SigmaBootstrapper** [comment]
sigma is skidded

**Comment by Melih-GMC2** [comment]
sigma is not skidded, it's sigma

**Comment by amogusman01** [comment]
sigma is the best client ever

**Comment by BlackPyxl1** [comment]
use Jello source code (Skidma Jello b1)
