### ISSUE TITLE
add zamorozka client

### ISSUE THREAD

**Issue by erxson** [chocopie69/Minecraft-Hacked-Client-Sources#4]

**Comment by chocopie69** [comment]
Among Us.

**Comment by Waveium** [comment]
> Among Us.

https://github.com/selfd3tach/zamorozka-client-deobfuscated heres the src from a leak on github

**Comment by chocopie69** [comment]
bruh this is unreadable, im not going to add any unreadable shits

**Comment by erxdev** [comment]
> bruh this is unreadable, im not going to add any unreadable shits

https://github.com/xWhitey/Zamorozka-0.5.3-src

**Comment by erxdev** [comment]
original

**Comment by erxdev** [comment]
leak by developer

**Comment by ENDER1355** [comment]
> > Among Us.
> 
> https://github.com/selfd3tach/zamorozka-client-deobfuscated heres the src from a leak on github

chocopie nigger

**Comment by ENDER1355** [comment]
[yes](gay.com)
