### ISSUE TITLE
Jigsaw uptodate sources

### ISSUE THREAD

**Issue by CallumlousTV** [chocopie69/Minecraft-Hacked-Client-Sources#5]

**Comment by chocopie69** [comment]
consider doing your mom
(also send me the latest jigsaw src codes in discord dms)

**Comment by CallumlousTV** [comment]
check dm i sent

**Comment by CallumlousTV** [comment]
Added Pull Request with changes, closing issue now.

**Comment by ENDER1355** [comment]
> _No description provided._

nigga
